version: '3.8'
services:
  app:
    container_name: coffeeTime
    restart: always
    build: .
    ports:
      - '7000:7000'
    external_links:
      - mongo
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'